// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blend_pixels`

Future<void> addWatermark(
        {required String srcPath,
        required String watermarkPath,
        required String outputPath}) =>
    RustLib.instance.api.crateApiImageAddWatermark(
        srcPath: srcPath, watermarkPath: watermarkPath, outputPath: outputPath);
